packages:
  - 'packages/*'
  - 'services/*'
  - 'e2e'
allowBuilds:
  '@google/genai': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  protobufjs: true
